# Generated by Django 2.2.17 on 2021-02-09 09:18

from django.db import migrations
import networkapi.buyersguide.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0034_buyersguidepage_dark_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalproductpage',
            name='user_friendly_privacy_policy_de',
            field=networkapi.buyersguide.fields.ExtendedYesNoField(help_text='Does this product have a user-friendly privacy policy?', null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='user_friendly_privacy_policy_en',
            field=networkapi.buyersguide.fields.ExtendedYesNoField(help_text='Does this product have a user-friendly privacy policy?', null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='user_friendly_privacy_policy_es',
            field=networkapi.buyersguide.fields.ExtendedYesNoField(help_text='Does this product have a user-friendly privacy policy?', null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='user_friendly_privacy_policy_fr',
            field=networkapi.buyersguide.fields.ExtendedYesNoField(help_text='Does this product have a user-friendly privacy policy?', null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='user_friendly_privacy_policy_fy_NL',
            field=networkapi.buyersguide.fields.ExtendedYesNoField(help_text='Does this product have a user-friendly privacy policy?', null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='user_friendly_privacy_policy_nl',
            field=networkapi.buyersguide.fields.ExtendedYesNoField(help_text='Does this product have a user-friendly privacy policy?', null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='user_friendly_privacy_policy_pl',
            field=networkapi.buyersguide.fields.ExtendedYesNoField(help_text='Does this product have a user-friendly privacy policy?', null=True),
        ),
        migrations.AddField(
            model_name='generalproductpage',
            name='user_friendly_privacy_policy_pt',
            field=networkapi.buyersguide.fields.ExtendedYesNoField(help_text='Does this product have a user-friendly privacy policy?', null=True),
        ),
    ]
