# Generated by Django 2.2.16 on 2020-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0002_auto_20200915_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='snippet_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='snippet_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='snippet_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='snippet_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='snippet_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='snippet_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='snippet_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='snippet_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_de',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_es',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_fr',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_fy_NL',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_nl',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_pl',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_pt',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
