# Generated by Django 2.2.16 on 2020-09-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0003_auto_20200915_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description of the product category. Max. 300 characters.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description of the product category. Max. 300 characters.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='description_es',
            field=models.TextField(blank=True, help_text='Description of the product category. Max. 300 characters.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Description of the product category. Max. 300 characters.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='description_fy_NL',
            field=models.TextField(blank=True, help_text='Description of the product category. Max. 300 characters.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='description_nl',
            field=models.TextField(blank=True, help_text='Description of the product category. Max. 300 characters.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='description_pl',
            field=models.TextField(blank=True, help_text='Description of the product category. Max. 300 characters.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='description_pt',
            field=models.TextField(blank=True, help_text='Description of the product category. Max. 300 characters.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_fy_NL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersguideproductcategory',
            name='name_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='child_rules_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='child_rules_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='child_rules_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='child_rules_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='child_rules_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='child_rules_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='child_rules_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='child_rules_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='collects_biometrics_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='collects_biometrics_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='collects_biometrics_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='collects_biometrics_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='collects_biometrics_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='collects_biometrics_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='collects_biometrics_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='collects_biometrics_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='delete_data_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='delete_data_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='delete_data_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='delete_data_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='delete_data_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='delete_data_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='delete_data_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='delete_data_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='productprivacypolicylink',
            name='label_de',
            field=models.CharField(help_text='Label for this link on the product page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productprivacypolicylink',
            name='label_en',
            field=models.CharField(help_text='Label for this link on the product page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productprivacypolicylink',
            name='label_es',
            field=models.CharField(help_text='Label for this link on the product page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productprivacypolicylink',
            name='label_fr',
            field=models.CharField(help_text='Label for this link on the product page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productprivacypolicylink',
            name='label_fy_NL',
            field=models.CharField(help_text='Label for this link on the product page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productprivacypolicylink',
            name='label_nl',
            field=models.CharField(help_text='Label for this link on the product page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productprivacypolicylink',
            name='label_pl',
            field=models.CharField(help_text='Label for this link on the product page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productprivacypolicylink',
            name='label_pt',
            field=models.CharField(help_text='Label for this link on the product page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='easy_to_learn_and_use_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='easy_to_learn_and_use_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='easy_to_learn_and_use_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='easy_to_learn_and_use_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='easy_to_learn_and_use_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='easy_to_learn_and_use_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='easy_to_learn_and_use_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='easy_to_learn_and_use_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='handles_recordings_how_de',
            field=models.TextField(blank=True, help_text='How does this software handle your recordings', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='handles_recordings_how_en',
            field=models.TextField(blank=True, help_text='How does this software handle your recordings', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='handles_recordings_how_es',
            field=models.TextField(blank=True, help_text='How does this software handle your recordings', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='handles_recordings_how_fr',
            field=models.TextField(blank=True, help_text='How does this software handle your recordings', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='handles_recordings_how_fy_NL',
            field=models.TextField(blank=True, help_text='How does this software handle your recordings', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='handles_recordings_how_nl',
            field=models.TextField(blank=True, help_text='How does this software handle your recordings', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='handles_recordings_how_pl',
            field=models.TextField(blank=True, help_text='How does this software handle your recordings', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='handles_recordings_how_pt',
            field=models.TextField(blank=True, help_text='How does this software handle your recordings', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='host_controls_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='host_controls_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='host_controls_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='host_controls_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='host_controls_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='host_controls_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='host_controls_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='host_controls_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='medical_privacy_compliant_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='medical_privacy_compliant_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='medical_privacy_compliant_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='medical_privacy_compliant_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='medical_privacy_compliant_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='medical_privacy_compliant_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='medical_privacy_compliant_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='medical_privacy_compliant_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='recording_alert_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='recording_alert_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='recording_alert_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='recording_alert_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='recording_alert_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='recording_alert_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='recording_alert_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='recording_alert_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='signup_methods_helptext_de',
            field=models.TextField(blank=True, help_text='Describe the kind of contact information requirements for signing up for this product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='signup_methods_helptext_en',
            field=models.TextField(blank=True, help_text='Describe the kind of contact information requirements for signing up for this product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='signup_methods_helptext_es',
            field=models.TextField(blank=True, help_text='Describe the kind of contact information requirements for signing up for this product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='signup_methods_helptext_fr',
            field=models.TextField(blank=True, help_text='Describe the kind of contact information requirements for signing up for this product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='signup_methods_helptext_fy_NL',
            field=models.TextField(blank=True, help_text='Describe the kind of contact information requirements for signing up for this product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='signup_methods_helptext_nl',
            field=models.TextField(blank=True, help_text='Describe the kind of contact information requirements for signing up for this product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='signup_methods_helptext_pl',
            field=models.TextField(blank=True, help_text='Describe the kind of contact information requirements for signing up for this product', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='signup_methods_helptext_pt',
            field=models.TextField(blank=True, help_text='Describe the kind of contact information requirements for signing up for this product', max_length=5000, null=True),
        ),
    ]
