# Generated by Django 2.2.16 on 2020-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0004_auto_20200915_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='how_does_it_share_de',
            field=models.CharField(blank=True, help_text='How does this product handle data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_does_it_share_en',
            field=models.CharField(blank=True, help_text='How does this product handle data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_does_it_share_es',
            field=models.CharField(blank=True, help_text='How does this product handle data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_does_it_share_fr',
            field=models.CharField(blank=True, help_text='How does this product handle data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_does_it_share_fy_NL',
            field=models.CharField(blank=True, help_text='How does this product handle data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_does_it_share_nl',
            field=models.CharField(blank=True, help_text='How does this product handle data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_does_it_share_pl',
            field=models.CharField(blank=True, help_text='How does this product handle data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_does_it_share_pt',
            field=models.CharField(blank=True, help_text='How does this product handle data?', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='share_data_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='share_data_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='share_data_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='share_data_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='share_data_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='share_data_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='share_data_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='share_data_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_friendly_privacy_policy_helptext_de',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_friendly_privacy_policy_helptext_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_friendly_privacy_policy_helptext_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_friendly_privacy_policy_helptext_fr',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_friendly_privacy_policy_helptext_fy_NL',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_friendly_privacy_policy_helptext_nl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_friendly_privacy_policy_helptext_pl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_friendly_privacy_policy_helptext_pt',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='worst_case_de',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='worst_case_en',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='worst_case_es',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='worst_case_fr',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='worst_case_fy_NL',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='worst_case_nl',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='worst_case_pl',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='worst_case_pt',
            field=models.CharField(blank=True, help_text="What's the worst thing that could happen by using this product?", max_length=5000, null=True),
        ),
    ]
